<a href="https://colab.research.google.com/github/JraHike76/DS-Unit-1-Sprint-1-Data-Wrangling-and-Storytelling/blob/master/module3-join-and-reshape-data/Jay_Adamo_Join_and_Reshape_Data_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Lambda School Data Science

*Unit 1, Sprint 1, Module 3*

---

# Join and Reshape datasets

Objectives
- concatenate data with pandas
- merge data with pandas
-  understand tidy data formatting
-  melt and pivot data with pandas

Links
- [Pandas Cheat Sheet](https://github.com/pandas-dev/pandas/blob/master/doc/cheatsheet/Pandas_Cheat_Sheet.pdf)
- [Tidy Data](https://en.wikipedia.org/wiki/Tidy_data)
  - Combine Data Sets: Standard Joins
  - Tidy Data
  - Reshaping Data
- Python Data Science Handbook
  - [Chapter 3.6](https://jakevdp.github.io/PythonDataScienceHandbook/03.06-concat-and-append.html), Combining Datasets: Concat and Append
  - [Chapter 3.7](https://jakevdp.github.io/PythonDataScienceHandbook/03.07-merge-and-join.html), Combining Datasets: Merge and Join
  - [Chapter 3.8](https://jakevdp.github.io/PythonDataScienceHandbook/03.08-aggregation-and-grouping.html), Aggregation and Grouping
  - [Chapter 3.9](https://jakevdp.github.io/PythonDataScienceHandbook/03.09-pivot-tables.html), Pivot Tables
  
Reference
- Pandas Documentation: [Reshaping and Pivot Tables](https://pandas.pydata.org/pandas-docs/stable/reshaping.html)
- Modern Pandas, Part 5: [Tidy Data](https://tomaugspurger.github.io/modern-5-tidy.html)

In [8]:
!wget https://s3.amazonaws.com/instacart-datasets/instacart_online_grocery_shopping_2017_05_01.tar.gz

--2020-05-07 13:25:29--  https://s3.amazonaws.com/instacart-datasets/instacart_online_grocery_shopping_2017_05_01.tar.gz
Resolving s3.amazonaws.com (s3.amazonaws.com)... 52.216.106.13
Connecting to s3.amazonaws.com (s3.amazonaws.com)|52.216.106.13|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 205548478 (196M) [application/x-gzip]
Saving to: ‘instacart_online_grocery_shopping_2017_05_01.tar.gz’

instacart_online_gr 100%[===================>] 196.03M  46.2MB/s    in 4.2s    

2020-05-07 13:25:34 (46.9 MB/s) - ‘instacart_online_grocery_shopping_2017_05_01.tar.gz’ saved [205548478/205548478]



In [9]:
!tar --gunzip --extract --verbose --file=instacart_online_grocery_shopping_2017_05_01.tar.gz

instacart_2017_05_01/
instacart_2017_05_01/._aisles.csv
instacart_2017_05_01/aisles.csv
instacart_2017_05_01/._departments.csv
instacart_2017_05_01/departments.csv
instacart_2017_05_01/._order_products__prior.csv
instacart_2017_05_01/order_products__prior.csv
instacart_2017_05_01/._order_products__train.csv
instacart_2017_05_01/order_products__train.csv
instacart_2017_05_01/._orders.csv
instacart_2017_05_01/orders.csv
instacart_2017_05_01/._products.csv
instacart_2017_05_01/products.csv


In [10]:
%cd instacart_2017_05_01

/content/instacart_2017_05_01


In [11]:
!ls -lh *.csv

-rw-r--r-- 1 502 staff 2.6K May  2  2017 aisles.csv
-rw-r--r-- 1 502 staff  270 May  2  2017 departments.csv
-rw-r--r-- 1 502 staff 551M May  2  2017 order_products__prior.csv
-rw-r--r-- 1 502 staff  24M May  2  2017 order_products__train.csv
-rw-r--r-- 1 502 staff 104M May  2  2017 orders.csv
-rw-r--r-- 1 502 staff 2.1M May  2  2017 products.csv


# Assignment

## Join Data Practice

These are the top 10 most frequently ordered products. How many times was each ordered? 

1. Banana
2. Bag of Organic Bananas
3. Organic Strawberries
4. Organic Baby Spinach 
5. Organic Hass Avocado
6. Organic Avocado
7. Large Lemon 
8. Strawberries
9. Limes 
10. Organic Whole Milk

First, write down which columns you need and which dataframes have them.

Next, merge these into a single dataframe.

Then, use pandas functions from the previous lesson to get the counts of the top 10 most frequently ordered products.

In [0]:
import pandas as pd


In [13]:
#I will need to look at order_products_train 
order_products_train = pd.read_csv('order_products__train.csv')
print(order_products_train.shape)
order_products_train.head()

(1384617, 4)


order_id  product_id  add_to_cart_order  reordered
0         1       49302                  1          1
1         1       11109                  2          1
2         1       10246                  3          0
3         1       49683                  4          0
4         1       43633                  5          1

In [14]:
#and order_products_prior
order_products_prior = pd.read_csv('order_products__prior.csv')
print(order_products_prior.shape)
order_products_prior.head()

(32434489, 4)


order_id  product_id  add_to_cart_order  reordered
0         2       33120                  1          1
1         2       28985                  2          1
2         2        9327                  3          0
3         2       45918                  4          1
4         2       30035                  5          0

In [15]:
#I also need to look at products
products = pd.read_csv('products.csv')
print(products.shape)
products.head()

(49688, 4)


product_id  ... department_id
0           1  ...            19
1           2  ...            13
2           3  ...             7
3           4  ...             1
4           5  ...            13

[5 rows x 4 columns]

These are the top 10 most frequently ordered products. How many times was each ordered?

Banana,
Bag of Organic Bananas,
Organic Strawberries,
Organic Baby Spinach,
Organic Hass Avocado,
Organic Avocado,
Large Lemon,
Strawberries,
Limes,
Organic Whole Milk

First, write down which columns you need and which dataframes have them.

Next, merge these into a single dataframe.

In [0]:
#I will need to concatenate ordered_product__prior and ordered_products__train 
order_products = pd.concat([order_products_prior, order_products_train])

In [17]:
#inspection time
order_products_prior.shape

(32434489, 4)

In [18]:
order_products_train.shape

(1384617, 4)

In [19]:
order_products.shape

(33819106, 4)

In [20]:
products.shape

(49688, 4)

These are the top 10 most frequently ordered products. How many times was each ordered?

Banana
Bag of Organic Bananas
Organic Strawberries
Organic Baby Spinach
Organic Hass Avocado
Organic Avocado
Large Lemon
Strawberries
Limes
Organic Whole Milk
First, write down which columns you need and which dataframes have them.

Next, merge these into a single dataframe.

In [0]:
#I only need product name, product id and items added to the cart so I will have to slim down the data frames

In [22]:
order_products.head()

order_id  product_id  add_to_cart_order  reordered
0         2       33120                  1          1
1         2       28985                  2          1
2         2        9327                  3          0
3         2       45918                  4          1
4         2       30035                  5          0

In [23]:
order_products = order_products[['product_id','add_to_cart_order']]
order_products.head()

product_id  add_to_cart_order
0       33120                  1
1       28985                  2
2        9327                  3
3       45918                  4
4       30035                  5

These are the top 10 most frequently ordered products. How many times was each ordered?

Banana
Bag of Organic Bananas
Organic Strawberries
Organic Baby Spinach
Organic Hass Avocado
Organic Avocado
Large Lemon
Strawberries
Limes
Organic Whole Milk
First, write down which columns you need and which dataframes have them.

Next, merge these into a single dataframe.

In [24]:
#now I will slim down products to only show product name and id
products = products[['product_name','product_id']]
products.head()

product_name  product_id
0                         Chocolate Sandwich Cookies           1
1                                   All-Seasons Salt           2
2               Robust Golden Unsweetened Oolong Tea           3
3  Smart Ones Classic Favorites Mini Rigatoni Wit...           4
4                          Green Chile Anytime Sauce           5

In [25]:
#all 3 dataframes contain a unique identifier product_id so I can merge the order_products and products
most_frequent_products = pd.merge(order_products,products)
most_frequent_products.head(20)

product_id  add_to_cart_order        product_name
0        33120                  1  Organic Egg Whites
1        33120                  5  Organic Egg Whites
2        33120                 13  Organic Egg Whites
3        33120                  5  Organic Egg Whites
4        33120                 28  Organic Egg Whites
5        33120                  2  Organic Egg Whites
6        33120                  7  Organic Egg Whites
7        33120                  5  Organic Egg Whites
8        33120                  1  Organic Egg Whites
9        33120                  4  Organic Egg Whites
10       33120                  3  Organic Egg Whites
11       33120                 29  Organic Egg Whites
12       33120                  3  Organic Egg Whites
13       33120                  3  Organic Egg Whites
14       33120                  5  Organic Egg Whites
15       33120                 14  Organic Egg Whites
16       33120                  5  Organic Egg Whites
17       33120                  1  Organic Egg Whites
18       33120                  6  Organic Egg Whites
19       33120                 20  Organic Egg Whites

These are the top 10 most frequently ordered products. How many times was each ordered?

Banana
Bag of Organic Bananas
Organic Strawberries
Organic Baby Spinach
Organic Hass Avocado
Organic Avocado
Large Lemon
Strawberries
Limes
Organic Whole Milk
First, write down which columns you need and which dataframes have them.

Next, merge these into a single dataframe.

In [26]:
most_frequent_products['product_name'].value_counts().head(10)

Banana                    491291
Bag of Organic Bananas    394930
Organic Strawberries      275577
Organic Baby Spinach      251705
Organic Hass Avocado      220877
Organic Avocado           184224
Large Lemon               160792
Strawberries              149445
Limes                     146660
Organic Whole Milk        142813
Name: product_name, dtype: int64

These are the top 10 most frequently ordered products. How many times was each ordered?

Banana,
Bag of Organic Bananas,
Organic Strawberries,
Organic Baby Spinach,
Organic Hass Avocado,
Organic Avocado,
Large Lemon,
Strawberries,
Limes,
Organic Whole Milk

First, write down which columns you need and which dataframes have them.

Next, merge these into a single dataframe.

In [0]:
#I stopped here because the answer is above
#I worked with a fellow student and we could not figure out how to set up a df 
#to only include those top 10 products and their orders 

In [0]:
#after thinking about this I am not answering the question completely
#I will try to come up with code to run the dataframe that includes my value counts

#I have looked it up and cannot find much information and the lesson example was far different
#I hope that my work has shown that I can concatenate and merge dataframes and find the values I need
#I may try and come back to this after completing the next section but today is module 4 and I have to work on the study guide

#see my attempts below

In [39]:
top_product_orders = most_frequent_products['product_name'].value_counts()
top_product_orders.head()

Banana                    491291
Bag of Organic Bananas    394930
Organic Strawberries      275577
Organic Baby Spinach      251705
Organic Hass Avocado      220877
Name: product_name, dtype: int64

In [40]:
top_product_orders = pd.DataFrame(top_product_orders, columns = ['Products','Orders'])
top_product_orders.head()

Empty DataFrame
Columns: [Products, Orders]
Index: []

In [41]:
top_product_orders = top_product_orders(pd.DataFrame(top_product_orders, columns = ['Products','Orders']))
top_product_orders.head()

TypeError: ignored

In [44]:
top_product_orders = pd.DataFrame(top_product_orders, columns = ['Products','Orders'])
top_product_orders.head()

Empty DataFrame
Columns: [Products, Orders]
Index: []

## Reshape Data Section

- Replicate the lesson code. Remember, if you haven't followed along typing out what we did during lecture, do that now to get more repetition with the syntax.
- Take table 2 (the transpose of table 1) and practice changing it into Tidy format and back again. You should not use the transpose operation anywhere in this code:
 - Table 2 --> Tidy
 - Tidy --> Table 2
- Load seaborn's `flights` dataset by running the cell below. Then create a pivot table showing the number of passengers by month and year. Use year for the index and month for the columns. You've done it right if you get 112 passengers for January 1949 and 432 passengers for December 1960.

In [59]:
import pandas as pd
import numpy as np

table1 = pd.DataFrame(
    [[np.nan, 2],
     [16,    11], 
     [3,      1]],
    index=['John Smith', 'Jane Doe', 'Mary Johnson'], 
    columns=['treatmenta', 'treatmentb'])

table2 = table1.T

table2

John Smith  Jane Doe  Mary Johnson
treatmenta         NaN      16.0           3.0
treatmentb         2.0      11.0           1.0

In [60]:
# table2 -> tidy
#adding index as new column
table2 = table2.reset_index()

table2

index  John Smith  Jane Doe  Mary Johnson
0  treatmenta         NaN      16.0           3.0
1  treatmentb         2.0      11.0           1.0

In [61]:
#using melt with the unique identidier 'index'
tidy2 = table2.melt(id_vars='index')

tidy2

index      variable  value
0  treatmenta    John Smith    NaN
1  treatmentb    John Smith    2.0
2  treatmenta      Jane Doe   16.0
3  treatmentb      Jane Doe   11.0
4  treatmenta  Mary Johnson    3.0
5  treatmentb  Mary Johnson    1.0

In [64]:
# tidy -> table2
wide = tidy2.pivot_table(index=['John Smith', 'Jane Doe', 'Mary Johnson'], 
    columns=['treatmenta', 'treatmentb'])

wide

KeyError: ignored

Load seaborn's flights dataset by running the cell below. Then create a pivot table showing the number of passengers by month and year. Use year for the index and month for the columns. You've done it right if you get 112 passengers for January 1949 and 432 passengers for December 1960.

In [66]:
import seaborn as sns
flights = sns.load_dataset('flights')
flights

year      month  passengers
0    1949    January         112
1    1949   February         118
2    1949      March         132
3    1949      April         129
4    1949        May         121
..    ...        ...         ...
139  1960     August         606
140  1960  September         508
141  1960    October         461
142  1960   November         390
143  1960   December         432

[144 rows x 3 columns]

In [67]:
# Flights Pivot Table
passengers = flights.pivot_table(index='year', columns='month')

passengers

passengers                       ...                                    
month    January February March April  ... September October November December
year                                   ...                                    
1949         112      118   132   129  ...       136     119      104      118
1950         115      126   141   135  ...       158     133      114      140
1951         145      150   178   163  ...       184     162      146      166
1952         171      180   193   181  ...       209     191      172      194
1953         196      196   236   235  ...       237     211      180      201
1954         204      188   235   227  ...       259     229      203      229
1955         242      233   267   269  ...       312     274      237      278
1956         284      277   317   313  ...       355     306      271      306
1957         315      301   356   348  ...       404     347      305      336
1958         340      318   362   348  ...       404     359      310      337
1959         360      342   406   396  ...       463     407      362      405
1960         417      391   419   461  ...       508     461      390      432

[12 rows x 12 columns]

You've done it right if you get 112 passengers for January 1949 and 432 passengers for December 1960.

In [0]:
#whooooooo!!!

## Join Data Stretch Challenge

The [Instacart blog post](https://tech.instacart.com/3-million-instacart-orders-open-sourced-d40d29ead6f2) has a visualization of "**Popular products** purchased earliest in the day (green) and latest in the day (red)." 

The post says,

> "We can also see the time of day that users purchase specific products.

> Healthier snacks and staples tend to be purchased earlier in the day, whereas ice cream (especially Half Baked and The Tonight Dough) are far more popular when customers are ordering in the evening.

> **In fact, of the top 25 latest ordered products, the first 24 are ice cream! The last one, of course, is a frozen pizza.**"

Your challenge is to reproduce the list of the top 25 latest ordered popular products.

We'll define "popular products" as products with more than 2,900 orders.



In [0]:
##### YOUR CODE HERE #####

## Reshape Data Stretch Challenge

_Try whatever sounds most interesting to you!_

- Replicate more of Instacart's visualization showing "Hour of Day Ordered" vs "Percent of Orders by Product"
- Replicate parts of the other visualization from [Instacart's blog post](https://tech.instacart.com/3-million-instacart-orders-open-sourced-d40d29ead6f2), showing "Number of Purchases" vs "Percent Reorder Purchases"
- Get the most recent order for each user in Instacart's dataset. This is a useful baseline when [predicting a user's next order](https://www.kaggle.com/c/instacart-market-basket-analysis)
- Replicate parts of the blog post linked at the top of this notebook: [Modern Pandas, Part 5: Tidy Data](https://tomaugspurger.github.io/modern-5-tidy.html)

In [0]:
##### YOUR CODE HERE #####