<a href="https://colab.research.google.com/github/jovanrajic/DS-Unit-1-Sprint-1-Data-Wrangling-and-Storytelling/blob/master/module3-join-and-reshape-data/LS_DS_113_Join_and_Reshape_Data_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Lambda School Data Science

*Unit 1, Sprint 1, Module 3*

---

# Join and Reshape datasets

Objectives
- concatenate data with pandas
- merge data with pandas
-  understand tidy data formatting
-  melt and pivot data with pandas

Links
- [Pandas Cheat Sheet](https://github.com/pandas-dev/pandas/blob/master/doc/cheatsheet/Pandas_Cheat_Sheet.pdf)
- [Tidy Data](https://en.wikipedia.org/wiki/Tidy_data)
  - Combine Data Sets: Standard Joins
  - Tidy Data
  - Reshaping Data
- Python Data Science Handbook
  - [Chapter 3.6](https://jakevdp.github.io/PythonDataScienceHandbook/03.06-concat-and-append.html), Combining Datasets: Concat and Append
  - [Chapter 3.7](https://jakevdp.github.io/PythonDataScienceHandbook/03.07-merge-and-join.html), Combining Datasets: Merge and Join
  - [Chapter 3.8](https://jakevdp.github.io/PythonDataScienceHandbook/03.08-aggregation-and-grouping.html), Aggregation and Grouping
  - [Chapter 3.9](https://jakevdp.github.io/PythonDataScienceHandbook/03.09-pivot-tables.html), Pivot Tables
  
Reference
- Pandas Documentation: [Reshaping and Pivot Tables](https://pandas.pydata.org/pandas-docs/stable/reshaping.html)
- Modern Pandas, Part 5: [Tidy Data](https://tomaugspurger.github.io/modern-5-tidy.html)

In [ ]:
!wget https://s3.amazonaws.com/instacart-datasets/instacart_online_grocery_shopping_2017_05_01.tar.gz

--2020-08-05 23:43:42--  https://s3.amazonaws.com/instacart-datasets/instacart_online_grocery_shopping_2017_05_01.tar.gz
Resolving s3.amazonaws.com (s3.amazonaws.com)... 52.216.94.253
Connecting to s3.amazonaws.com (s3.amazonaws.com)|52.216.94.253|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 205548478 (196M) [application/x-gzip]
Saving to: ‘instacart_online_grocery_shopping_2017_05_01.tar.gz.1’

instacart_online_gr 100%[===================>] 196.03M  47.5MB/s    in 4.2s    

2020-08-05 23:43:47 (47.0 MB/s) - ‘instacart_online_grocery_shopping_2017_05_01.tar.gz.1’ saved [205548478/205548478]



In [ ]:
!tar --gunzip --extract --verbose --file=instacart_online_grocery_shopping_2017_05_01.tar.gz

instacart_2017_05_01/
instacart_2017_05_01/._aisles.csv
instacart_2017_05_01/aisles.csv
instacart_2017_05_01/._departments.csv
instacart_2017_05_01/departments.csv
instacart_2017_05_01/._order_products__prior.csv
instacart_2017_05_01/order_products__prior.csv
instacart_2017_05_01/._order_products__train.csv
instacart_2017_05_01/order_products__train.csv
instacart_2017_05_01/._orders.csv
instacart_2017_05_01/orders.csv
instacart_2017_05_01/._products.csv
instacart_2017_05_01/products.csv


In [ ]:
%cd instacart_2017_05_01

/content/instacart_2017_05_01


In [ ]:
!ls -lh *.csv

-rw-r--r-- 1 502 staff 2.6K May  2  2017 aisles.csv
-rw-r--r-- 1 502 staff  270 May  2  2017 departments.csv
-rw-r--r-- 1 502 staff 551M May  2  2017 order_products__prior.csv
-rw-r--r-- 1 502 staff  24M May  2  2017 order_products__train.csv
-rw-r--r-- 1 502 staff 104M May  2  2017 orders.csv
-rw-r--r-- 1 502 staff 2.1M May  2  2017 products.csv


# Assignment

## Join Data Practice

These are the top 10 most frequently ordered products. How many times was each ordered? 

1. Banana
2. Bag of Organic Bananas
3. Organic Strawberries
4. Organic Baby Spinach 
5. Organic Hass Avocado
6. Organic Avocado
7. Large Lemon 
8. Strawberries
9. Limes 
10. Organic Whole Milk

First, write down which columns you need and which dataframes have them.

Next, merge these into a single dataframe.

Then, use pandas functions from the previous lesson to get the counts of the top 10 most frequently ordered products.

In [ ]:

import pandas as pd
import numpy as np


In [ ]:
# 

In [ ]:
order_products_prior = pd.read_csv("order_products__prior.csv")

print(order_products_prior.shape)
order_products_prior.head()

(32434489, 4)


order_id  product_id  add_to_cart_order  reordered
0         2       33120                  1          1
1         2       28985                  2          1
2         2        9327                  3          0
3         2       45918                  4          1
4         2       30035                  5          0

In [ ]:
order_products_train = pd.read_csv("order_products__train.csv")

print(order_products_train.shape)
order_products_train.head()

(1384617, 4)


order_id  product_id  add_to_cart_order  reordered
0         1       49302                  1          1
1         1       11109                  2          1
2         1       10246                  3          0
3         1       49683                  4          0
4         1       43633                  5          1

In [ ]:

orders = pd.read_csv("orders.csv")

print(orders.shape)
orders.head()

(3421083, 7)


order_id  user_id  ... order_hour_of_day  days_since_prior_order
0   2539329        1  ...                 8                     NaN
1   2398795        1  ...                 7                    15.0
2    473747        1  ...                12                    21.0
3   2254736        1  ...                 7                    29.0
4    431534        1  ...                15                    28.0

[5 rows x 7 columns]

In [ ]:
products = pd.read_csv("products.csv")

print(products.shape)
products.head()

(49688, 4)


product_id  ... department_id
0           1  ...            19
1           2  ...            13
2           3  ...             7
3           4  ...             1
4           5  ...            13

[5 rows x 4 columns]

In [ ]:
order_products = pd.concat([order_products_prior, order_products_train])

print(order_products.shape)


(33819106, 4)


In [ ]:
# Merging "order_products" and "orders" dataframes

merge_ord = pd.merge(orders, order_products , how="inner", on= "order_id")

merge_ord.head()

order_id  user_id eval_set  ...  product_id  add_to_cart_order  reordered
0   2539329        1    prior  ...         196                  1          0
1   2539329        1    prior  ...       14084                  2          0
2   2539329        1    prior  ...       12427                  3          0
3   2539329        1    prior  ...       26088                  4          0
4   2539329        1    prior  ...       26405                  5          0

[5 rows x 10 columns]

In [ ]:
# Merging "merge_ord" and "products" dataframes:

merge_op = pd.merge(merge_ord, products, how= "inner", on= "product_id")

merge_op.head(20)

order_id  user_id eval_set  ...  product_name  aisle_id  department_id
0    2539329        1    prior  ...          Soda        77              7
1    2398795        1    prior  ...          Soda        77              7
2     473747        1    prior  ...          Soda        77              7
3    2254736        1    prior  ...          Soda        77              7
4     431534        1    prior  ...          Soda        77              7
5    3367565        1    prior  ...          Soda        77              7
6     550135        1    prior  ...          Soda        77              7
7    3108588        1    prior  ...          Soda        77              7
8    2295261        1    prior  ...          Soda        77              7
9    2550362        1    prior  ...          Soda        77              7
10   1187899        1    train  ...          Soda        77              7
11   2968173       15    prior  ...          Soda        77              7
12   1870022       15    prior  ...          Soda        77              7
13   1911383       15    prior  ...          Soda        77              7
14   2715276       15    prior  ...          Soda        77              7
15    487368       15    prior  ...          Soda        77              7
16   2293453       19    prior  ...          Soda        77              7
17   1973799       19    prior  ...          Soda        77              7
18    532817       19    prior  ...          Soda        77              7
19   1573906       21    prior  ...          Soda        77              7

[20 rows x 13 columns]

In [ ]:
merge_op.tail(20)

order_id  user_id  ... aisle_id  department_id
33819086    461844   200351  ...       20             11
33819087    216145   205587  ...       20             11
33819088   2941852   200463  ...      114             17
33819089   2321285   203389  ...      114             17
33819090    609055   202557  ...       64              7
33819091   1928449   202557  ...       64              7
33819092   2222639   202557  ...       64              7
33819093    339942   202557  ...       64              7
33819094   2798193   202557  ...       64              7
33819095   2391791   202557  ...       64              7
33819096    576295   202557  ...       64              7
33819097    960088   202557  ...       64              7
33819098    343962   202557  ...       64              7
33819099   2329472   202557  ...       64              7
33819100    694731   202557  ...       64              7
33819101   1320836   202557  ...       64              7
33819102     31526   202557  ...       64              7
33819103    758936   203436  ...       50             19
33819104   2745165   203436  ...       50             19
33819105   3093936   205420  ...      130             14

[20 rows x 13 columns]

In [ ]:
# Getting 10 most ordered products:
print(merge_op["product_name"].value_counts(ascending= False)[:10])

Banana                    491291
Bag of Organic Bananas    394930
Organic Strawberries      275577
Organic Baby Spinach      251705
Organic Hass Avocado      220877
Organic Avocado           184224
Large Lemon               160792
Strawberries              149445
Limes                     146660
Organic Whole Milk        142813
Name: product_name, dtype: int64


## Reshape Data Section

- Replicate the lesson code. Remember, if you haven't followed along typing out what we did during lecture, do that now to get more repetition with the syntax.
- Take table 2 (the transpose of table 1) and practice changing it into Tidy format and back again. You should not use the transpose operation anywhere in this code:
 - Table 2 --> Tidy
 - Tidy --> Table 2
- Load seaborn's `flights` dataset by running the cell below. Then create a pivot table showing the number of passengers by month and year. Use year for the index and month for the columns. You've done it right if you get 112 passengers for January 1949 and 432 passengers for December 1960.

In [ ]:
import pandas as pd
import numpy as np

table1 = pd.DataFrame(
    [[np.nan, 2],
     [16,    11], 
     [3,      1]],
    index=['John Smith', 'Jane Doe', 'Mary Johnson'], 
    columns=['treatmenta', 'treatmentb'])

table2 = table1.T

table2

John Smith  Jane Doe  Mary Johnson
treatmenta         NaN      16.0           3.0
treatmentb         2.0      11.0           1.0

In [ ]:
#table2 -> tidy
table2 = table2.reset_index()

table2

index  John Smith  Jane Doe  Mary Johnson
0  treatmenta         NaN      16.0           3.0
1  treatmentb         2.0      11.0           1.0

In [ ]:
tidy2 = table2.melt(id_vars = "index", value_vars=["John Smith", "Jane Doe", "Mary Johnson"])

tidy2

index      variable  value
0  treatmenta    John Smith    NaN
1  treatmentb    John Smith    2.0
2  treatmenta      Jane Doe   16.0
3  treatmentb      Jane Doe   11.0
4  treatmenta  Mary Johnson    3.0
5  treatmentb  Mary Johnson    1.0

In [ ]:
tidy2 = tidy2.rename(columns={
    "index": "trt",
    "variable": "name",
    "value": "result"
})

tidy2

trt          name  result
0  treatmenta    John Smith     NaN
1  treatmentb    John Smith     2.0
2  treatmenta      Jane Doe    16.0
3  treatmentb      Jane Doe    11.0
4  treatmenta  Mary Johnson     3.0
5  treatmentb  Mary Johnson     1.0

In [ ]:
tidy2.trt = tidy2.trt.str.replace("treatment", '')

tidy2

trt          name  result
0   a    John Smith     NaN
1   b    John Smith     2.0
2   a      Jane Doe    16.0
3   b      Jane Doe    11.0
4   a  Mary Johnson     3.0
5   b  Mary Johnson     1.0

In [ ]:
# tidy -> table2
not_tidy2 = tidy2.pivot_table(index="trt", columns="name", values="result")

not_tidy2


name  Jane Doe  John Smith  Mary Johnson
trt                                     
a         16.0         NaN           3.0
b         11.0         2.0           1.0

In [ ]:
import seaborn as sns

In [ ]:
flights = sns.load_dataset('flights')

flights

year      month  passengers
0    1949    January         112
1    1949   February         118
2    1949      March         132
3    1949      April         129
4    1949        May         121
..    ...        ...         ...
139  1960     August         606
140  1960  September         508
141  1960    October         461
142  1960   November         390
143  1960   December         432

[144 rows x 3 columns]

In [ ]:
# Flights Pivot Table

flight_pv = flights.pivot_table(index="year", columns="month", values="passengers")

flight_pv

month  January  February  March  April  ...  September  October  November  December
year                                    ...                                        
1949       112       118    132    129  ...        136      119       104       118
1950       115       126    141    135  ...        158      133       114       140
1951       145       150    178    163  ...        184      162       146       166
1952       171       180    193    181  ...        209      191       172       194
1953       196       196    236    235  ...        237      211       180       201
1954       204       188    235    227  ...        259      229       203       229
1955       242       233    267    269  ...        312      274       237       278
1956       284       277    317    313  ...        355      306       271       306
1957       315       301    356    348  ...        404      347       305       336
1958       340       318    362    348  ...        404      359       310       337
1959       360       342    406    396  ...        463      407       362       405
1960       417       391    419    461  ...        508      461       390       432

[12 rows x 12 columns]

 You've done it right if you get 112 passengers for January 1949 and 432 passengers for December 1960.

## Join Data Stretch Challenge

The [Instacart blog post](https://tech.instacart.com/3-million-instacart-orders-open-sourced-d40d29ead6f2) has a visualization of "**Popular products** purchased earliest in the day (green) and latest in the day (red)." 

The post says,

> "We can also see the time of day that users purchase specific products.

> Healthier snacks and staples tend to be purchased earlier in the day, whereas ice cream (especially Half Baked and The Tonight Dough) are far more popular when customers are ordering in the evening.

> **In fact, of the top 25 latest ordered products, the first 24 are ice cream! The last one, of course, is a frozen pizza.**"

Your challenge is to reproduce the list of the top 25 latest ordered popular products.

We'll define "popular products" as products with more than 2,900 orders.



In [ ]:
##### YOUR CODE HERE #####

## Reshape Data Stretch Challenge

_Try whatever sounds most interesting to you!_

- Replicate more of Instacart's visualization showing "Hour of Day Ordered" vs "Percent of Orders by Product"
- Replicate parts of the other visualization from [Instacart's blog post](https://tech.instacart.com/3-million-instacart-orders-open-sourced-d40d29ead6f2), showing "Number of Purchases" vs "Percent Reorder Purchases"
- Get the most recent order for each user in Instacart's dataset. This is a useful baseline when [predicting a user's next order](https://www.kaggle.com/c/instacart-market-basket-analysis)
- Replicate parts of the blog post linked at the top of this notebook: [Modern Pandas, Part 5: Tidy Data](https://tomaugspurger.github.io/modern-5-tidy.html)

In [ ]:
##### YOUR CODE HERE #####